# Generated by Django 2.2.6 on 2019-11-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('endDate', models.DateTimeField()),
            ],
        ),
    ]
