# Generated by Django 2.2.2 on 2019-11-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionsiteapp', '0003_auto_20191122_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUsers',
        ),
    ]
