# Generated by Django 2.2.2 on 2019-11-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionsiteapp', '0005_siteusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
