# Generated by Django 2.2.6 on 2019-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionsiteapp', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
