# Generated by Django 2.2.6 on 2019-11-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionsiteapp', '0009_auto_20191128_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionsiteapp.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionsiteapp.SiteUsers')),
            ],
        ),
    ]
